#!/usr/bin/env python3
"""
Generate diverse Indian bank-style transaction strings per label.
Unique merchant phrasing improves grouped (template-safe) evaluation.
Output: data/financial_transaction_synthetic_templates.csv
"""
import csv
import random
import string
from collections import Counter


def ref_hex():
    return "".join(random.choices(string.hexdigits.lower(), k=8))


def amount_inr():
    return round(random.uniform(120.0, 98500.0), 2)


def row(text: str, label: str) -> dict:
    return {
        "Transaction_Text": f"{text} | Ref:{ref_hex()} | Amount: INR {amount_inr()}",
        "Label": label,
    }


def main():
    random.seed(2026)
    rows = []

    # --- Food: many merchants + channels ---
    food_templates = [
        "Zomato food order UPI debit",
        "Swiggy Instamart grocery debit",
        "Blinkit quick commerce payment",
        "BigBasket monthly subscription charge",
        "Dunzo delivery fee and order",
        "Domino's pizza online order",
        "McDonald's India card swipe",
        "KFC dine-in bill payment",
        "Subway sandwich order UPI",
        "Starbucks coffee reload",
        "Cafe Coffee Day outlet bill",
        "Barbeque Nation reservation prepay",
        "Haldiram's sweets purchase",
        "ITC Master Chef frozen foods",
        "Mother Dairy booth milk debit",
        "Nandini milk parlour UPI",
        "Local kirana store POS debit",
        "Reliance Fresh supermarket bill",
        "DMart grocery checkout",
        "Spencer's Retail food basket",
        "Foodpanda order settlement",
        "EatSure cloud kitchen debit",
        "Faasos wrap order payment",
        "Thalis and meals cloud kitchen",
        "FreshToHome fish and meat order",
        "Licious meat subscription debit",
        "Box8 meals subscription",
        "Freshmenu salad bowl order",
        "Behrouz Biryani order",
        "Ovenstory pizza UPI",
        "Wow Momo kiosk payment",
        "Chaayos tea and snacks",
        "Third Wave Coffee roasters",
        "Blue Tokai coffee beans order",
        "Instamart late night snacks",
        "Zepto 10 min grocery",
        "JioMart grocery UPI collect",
        "More supermarket self checkout",
        "Foodhall gourmet purchase",
        "Nature's Basket organic bill",
        "Amazon Fresh grocery order",
        "Flipkart Supermart staples",
        "Metro Cash and Carry wholesale",
        "Restaurant bill via Paytm",
        "UPI collect request from hotel kitchen",
        "Tiffin service monthly debit",
        "Catering advance for function",
        "Sweet shop festival order",
        "Ice cream parlour card tap",
        "Bakery bread and cake order",
        "Cloud kitchen aggregator payout",
        "Street food vendor UPI",
        "College canteen wallet top-up",
        "Office cafeteria meal pass",
        "Airport lounge food charge",
        "Railway station food plaza",
        "Highway toll plaza food court",
        "Movie multiplex popcorn combo",
        "Stadium snack counter debit",
        "Hospital canteen recharge",
        "Temple prasad counter donation food",
        "Wedding hall catering advance",
        "Corporate lunch Sodexo meal",
        "Zomato Gold membership food benefit",
        "Swiggy One membership fee",
        "Uber Eats order (legacy)",
        "Food aggregator cashback reversal",
        "Grocery cashback wallet debit",
        "Milk subscription daily debit",
        "Vegetable mandi UPI payment",
        "Fish market vendor collect",
        "Egg tray wholesale debit",
        "Atta chakki grinding charges",
        "Juice bar detox cleanse",
        "Salad subscription weekly",
        "Protein shake brand debit",
        "Energy bar vending machine",
        "Midnight snack delivery",
        "Hostel mess fee deduction",
        "PG mess monthly food charge",
        "Co-working pantry snacks",
        "Startup office pantry restock",
        "Team lunch reimbursement debit",
        "Client dinner restaurant bill",
        "Business lunch card charge",
        "Airline meal pre-book debit",
        "Train pantry car order",
        "Bus journey snack pack",
        "Ferry canteen purchase",
        "Resort buffet breakfast charge",
        "Hotel room service dinner",
        "Minibar consumption charge",
        "Cook salary advance food budget",
        "Maid grocery shopping debit",
        "Festival sweets bulk order",
        "Diwali mithai box purchase",
        "Holi thandai supplies",
        "Christmas cake order",
        "Eid biryani bulk order",
        "Navratri fasting food pack",
        "Pongal sugarcane and jaggery",
        "Onam sadya catering",
        "Baisakhi langar donation food",
        "Ganesh Chaturthi modak order",
        "Janmashtami milk sweets",
        "Rakhi family dinner bill",
        "New year party catering",
        "Birthday cake custom order",
        "Anniversary dinner fine dining",
        "Date night restaurant UPI",
        "Brunch cafe weekend debit",
        "High tea lounge charge",
        "Wine shop permit payment",
        "Beer pub tab settlement",
        "Microbrewery tasting flight",
        "Food blogger shoot expenses",
        "Recipe box subscription debit",
        "Meal kit delivery weekly",
        "Frozen momos wholesale",
        "Momos stall evening rush",
        "Pani puri cart UPI",
        "Chaat corner bill",
        "South Indian meals thali",
        "North Indian thali combo",
        "Biryani bucket family pack",
        "Dosa batter subscription",
        "Idli sambar breakfast combo",
        "Paratha breakfast tiffin",
        "Poha and jalebi breakfast",
        "Misal pav outlet debit",
        "Vada pav stall Mumbai",
        "Pav bhaji beach stall",
        "Kathi roll Kolkata street",
        "Momos Darjeeling style",
        "Chole bhature Delhi outlet",
        "Rajma chawal home delivery",
        "Dal makhani butter naan set",
        "Tandoori chicken grill order",
        "Fish curry coastal meal",
        "Prawn fry restaurant bill",
        "Crab masala seasonal special",
        "Mutton biryani premium",
        "Chicken tikka platter",
        "Paneer tikka starter",
        "Veg platter buffet",
        "Jain meal special order",
        "Vegan bowl salad bar",
        "Gluten free bakery order",
        "Keto meal plan subscription",
        "Diabetic friendly meal kit",
        "Baby food formula purchase",
        "Senior citizen soft diet meal",
        "Hospital patient diet tray",
        "Gym protein shake bar",
        "Yoga retreat meals package",
        "Marathon energy gel pack",
        "Trekking packed meals",
        "Camping freeze dried food",
        "Airbnb host grocery stock",
        "Homestay breakfast charge",
        "Co-living kitchen supplies",
        "PG owner mess charges",
        "Landlord utility food share",
        "Splitwise settled food dues",
        "Friends group dinner split",
        "Office team pizza party",
        "Farewell cake and snacks",
        "Welcome kit snacks for new hire",
        "Conference tea coffee service",
        "Seminar lunch box order",
        "Workshop high tea catering",
        "Hackathon midnight pizza",
        "College fest food stall",
        "Tech meetup snacks sponsor",
        "NGO food drive supplies",
        "Blood donation camp refreshments",
        "Marathon aid station supplies",
        "School annual day snacks",
        "PTA meeting tea biscuits",
        "Sports day juice boxes",
        "Exam hall water bottles bulk",
        "Library cafe latte",
        "Museum cafe sandwich",
        "Zoo kiosk ice cream",
        "Aquarium cafe kids meal",
        "Theme park meal voucher",
        "Water park locker snack",
        "Ski resort hot chocolate",
        "Hill station maggi stall",
        "Beach shack coconut water",
        "River rafting packed lunch",
        "Wildlife safari packed meal",
        "Desert camp dinner under stars",
        "Houseboat Kerala meals",
        "Cruise deck dining charge",
        "Flight meal voucher debit",
        "Lounge access with meal",
        "Priority pass dining credit",
        "Credit card dining offer cashback reversal",
        "Debit card tap at food court",
        "NFC payment at bakery",
        "QR scan at juice shop",
        "UPI intent at restaurant",
        "UPI collect from dhaba",
        "PhonePe merchant food",
        "Google Pay merchant grocery",
        "Paytm QR kirana payment",
        "Amazon Pay UPI food order",
        "Cred pay food offer debit",
        "Slice card food cashback net",
        "OneCard dining rewards debit",
        "Fi money card cafe spend",
        "Jupiter neo bank UPI food",
        "Niyo global card meal abroad",
        "Forex card restaurant charge",
        "Multi currency wallet food",
    ]

    # --- Travel ---
    travel_templates = [
        "IRCTC e-ticket booking debit",
        "IRCTC Tatkal convenience fee",
        "RedBus intercity bus booking",
        "AbhiBus online ticket",
        "MakeMyTrip flight booking",
        "Cleartrip domestic airfare",
        "Goibibo hotel plus flight combo",
        "Yatra corporate travel booking",
        "EaseMyTrip holiday package",
        "Ixigo trains app booking",
        "Uber India ride hail",
        "Ola postpaid ride settlement",
        "Rapido bike taxi debit",
        "BluSmart EV cab charge",
        "Meru Cabs airport pickup",
        "Mega Cabs city ride",
        "Quick Ride carpool debit",
        "Shuttle app office commute",
        "Metro card recharge DMRC",
        "BEST bus pass monthly",
        "BMTC bus pass Bengaluru",
        "NMMT ferry ticket Mumbai",
        "Mumbai local season ticket",
        "Delhi metro smart card top-up",
        "Chennai metro QR ticket",
        "Hyderabad metro pass",
        "Kochi metro travel card",
        "Namma Metro Bengaluru top-up",
        "FASTag toll plaza debit",
        "NHAI toll recharge wallet",
        "Paytm FASTag top-up",
        "HPCL fuel pump card swipe",
        "IndianOil fuel UPI",
        "BPCL Speed fuel debit",
        "Shell petrol pump charge",
        "CNG station refill bill",
        "EV charging station session",
        "Ather grid charging debit",
        "Tata Power EZ charge",
        "Statiq EV charging UPI",
        "Zoomcar self drive rental",
        "Revv subscription car day",
        "Drivezy bike rental",
        "Bounce scooter rental",
        "Vogo scooter unlock fee",
        "Yulu bike unlock and ride",
        "Metro bike share Bengaluru",
        "Chalo bus live ticket",
        "Tummoc multimodal ticket",
        "Navi Mumbai ferry ticket",
        "Pawan Hans helicopter booking",
        "SpiceJet add-on baggage",
        "IndiGo seat selection fee",
        "Air India web check-in",
        "Vistara club upgrade",
        "Akasa Air meal pre-order",
        "AirAsia ancillary charge",
        "Blade India heli shuttle",
        "Charter flight deposit",
        "Ola outstation trip",
        "Uber intercity reserve",
        "Savaari cab booking",
        "Wiwigo outstation taxi",
        "Savaari driver tip UPI",
        "Railway retiring room booking",
        "IRCTC lounge access",
        "Airport prepaid taxi coupon",
        "Meru airport flat rate",
        "KSRTC Volvo online ticket",
        "RSRTC sleeper bus",
        "GSRTC express booking",
        "APSRTC Amaravati bus",
        "TNSTC SETC booking",
        "KSRTC Swift booking",
        "HRTC Volvo Manali",
        "JKSRTC Srinagar route",
        "NEKRTC night service",
        "WBTC electric bus ticket",
        "DTC cluster bus pass",
        "Chandigarh CTU pass",
        "PMPML Pune bus pass",
        "MSRTC Shivneri booking",
        "VRL Travels luxury bus",
        "SRS Travels sleeper",
        "Orange Travels AC bus",
        "Parveen Travels Tamil Nadu",
        "Kallada Travels Kerala",
        "Rajasthan Roadways booking",
        "Himachal Roadways ticket",
        "Uttarakhand transport booking",
        "Sikkim nationalised transport",
        "Assam ASTC online ticket",
        "Meghalaya transport booking",
        "Manipur MSRTC booking",
        "Tripura ST booking",
        "Mizoram ST online",
        "Nagaland ST booking",
        "Arunachal HRTC booking",
        "Ladakh inner line permit fee",
        "Andaman ferry ticket Port Blair",
        "Lakshadweep ship booking",
        "Goa Mopa airport taxi",
        "Goa Dabolim prepaid taxi",
        "Shimla toy train ticket",
        "Darjeeling Himalayan Railway",
        "Nilgiri Mountain Railway ticket",
        "Konkan railway tatkal",
        "Vande Bharat premium charge",
        "Rajdhani pantry car bill",
        "Shatabdi catering charge",
        "Tejas express meal",
        "Garib Rath bedding charge",
        "Sleeper class linen optional",
        "AC 3 tier upgrade fee",
        "Tatkal agent service charge",
        "Railway retiring room AC",
        "Station cloak room charge",
        "Platform ticket digital",
        "Suburban railway quarterly pass",
        "Mumbai monorail token",
        "Kolkata tram museum ticket",
        "Heritage toy train Darjeeling",
        "Ropeway Manali ticket",
        "Cable car Gulmarg",
        "Gondola ride booking",
        "Houseboat Alleppey advance",
        "Backwater cruise Kochi",
        "Wildlife safari jeep booking",
        "Desert camel ride Jaisalmer",
        "Paragliding billing advance",
        "Scuba diving Andaman slot",
        "Snorkelling Havelock booking",
        "Trekking permit fee Uttarakhand",
        "Forest entry fee Jim Corbett",
        "National park gypsy booking",
        "Wildlife guide fee debit",
        "Border area permit Sikkim",
        "Inner line permit Ladakh bike",
        "Bike rental Leh Ladakh",
        "Royal Enfield bullet rental",
        "Self drive car Spiti",
        "Tempo traveller hire Manali",
        "Innova crysta outstation",
        "Innova airport drop prepaid",
        "Corporate cab monthly invoice",
        "Employee transport shuttle fee",
        "Parking multilevel mall",
        "Airport parking P2 long stay",
        "Railway parking prepaid",
        "Bus stand cloak room",
        "Toll plaza monthly pass",
        "Expressway FASTag debit",
        "Yamuna expressway toll",
        "Mumbai Pune expressway toll",
        "Bangalore Mysore highway toll",
        "Chennai toll plaza debit",
        "Hyderabad ORR toll",
        "Delhi NCR toll tags",
        "Gurgaon toll plaza charge",
        "Noida expressway toll",
        "Jewar airport toll",
        "Sea link toll Mumbai",
        "Bandra Worli sea link",
        "Eastern freeway toll",
        "Western express highway toll",
        "Eastern peripheral expressway",
        "Delhi Meerut expressway toll",
        "Purvanchal expressway toll",
        "Agra Lucknow expressway toll",
        "Mumbai Goa highway toll",
        "Bangalore Chennai toll",
        "Visakhapatnam Araku ghat toll",
        "Shillong Cherrapunji road toll",
        "Guwahati Kaziranga toll",
        "Kochi Munnar ghat toll",
        "Ooty ghat road toll",
        "Kodaikanal hairpin toll",
        "Valparai hairpin bus toll",
    ]

    # --- Shopping ---
    shopping_templates = [
        "Amazon.in marketplace order",
        "Flipkart Big Billion Days order",
        "Myntra fashion sale debit",
        "Ajio style club purchase",
        "Nykaa beauty order",
        "Purplle cosmetics debit",
        "Tata CLiQ electronics",
        "Reliance Digital EMI down payment",
        "Croma store POS debit",
        "Vijay Sales TV purchase",
        "Poorvika mobiles debit",
        "Sangeetha mobiles Chennai",
        "UniverCell accessories",
        "MobileNXT repair parts",
        "iPlanet Apple reseller",
        "Imagine store AppleCare",
        "Poorvika iPhone trade-in",
        "Samsung shop online",
        "OnePlus store accessories",
        "Boat lifestyle earbuds",
        "Noise smartwatch order",
        "Fire-Boltt fitness band",
        "Lenovo laptop online",
        "HP world store debit",
        "Dell online outlet order",
        "Asus ROG accessories",
        "LG OLED TV installment",
        "Sony Bravia dealer debit",
        "Panasonic AC installation",
        "Voltas AC AMC renewal",
        "Blue Star water purifier",
        "Kent RO filter replacement",
        "Eureka Forbes vacuum",
        "Philips air fryer order",
        "Prestige cooker combo",
        "Pigeon kitchenware UPI",
        "Milton bottle bulk school",
        "Tupperware party order",
        "IKEA Hyderabad furniture",
        "HomeCentre decor purchase",
        "Urban Ladder sofa EMI",
        "Pepperfry wardrobe order",
        "Wakefit mattress online",
        "SleepyCat mattress debit",
        "Flo mattress trial debit",
        "Nilkamal plastic chairs",
        "Supreme furniture plastic",
        "Godrej Interio showroom",
        "Durian sofa leather order",
        "Hometown dining set",
        "HomeTown modular kitchen",
        "Livspace design fee advance",
        "Bonito Designs interior",
        "Asian Paints dealer debit",
        "Berger Paints contractor bill",
        "Nerolac emulsion bulk",
        "Dulux trade paint order",
        "Havells fan and lights",
        "Orient Electric cooler",
        "Bajaj Electricals iron",
        "Usha sewing machine order",
        "Morphy Richards mixer",
        "Butterfly mixer grinder",
        "Sujata mixer service parts",
        "Wonderchef cookware set",
        "Meyer cookware stainless",
        "Vinod cookware induction",
        "Hawkins pressure cooker",
        "Prestige induction cooktop",
        "Pigeon induction cooktop",
        "Borosil glassware set",
        "Treo tiffin stackable",
        "Milton tiffin combo",
        "Cello furniture plastic",
        "Nilkamal chair bulk office",
        "Supreme chair dealer",
        "Amazon basics HDMI cable",
        "Amazon basics backpack",
        "Flipkart smartbuy cable",
        "JioMart electronics accessories",
        "Reliance Smart Bazaar bulk",
        "DMart monthly stock-up",
        "Big Bazaar closing sale legacy",
        "Spencer's home essentials",
        "More Retail home care",
        "Metro wholesale cleaning supplies",
        "IKEA kids room furniture",
        "FirstCry baby gear order",
        "Hopscotch kids clothing",
        "Mothercare stroller order",
        "Decathlon sports gear",
        "Wildcraft rucksack order",
        "Skybags luggage online",
        "American Tourister suitcase",
        "Samsonite cabin bag",
        "VIP bags school bag",
        "Safari bags trolley",
        "Puma outlet sneakers",
        "Adidas originals store",
        "Nike factory outlet debit",
        "Reebok crossfit shoes",
        "Woodland boots seasonal",
        "Bata school shoes bulk",
        "Liberty shoes formal",
        "Metro shoes wedding",
        "Mochi shoes festive",
        "Regal shoes leather",
        "Hidesign wallet purchase",
        "Lavie handbags online",
        "Caprese bags debit",
        "Baggit tote order",
        "Wildcraft wallet combo",
        "Tanishq jewellery advance",
        "Malabar Gold purchase",
        "Kalyan Jewellers booking",
        "PC Jeweller gold coin",
        "Joyalukkas chain purchase",
        "Bhima jewellers necklace",
        "Reliance Jewels offer",
        "CaratLane online ring",
        "BlueStone diamond stud",
        "Melorra daily wear gold",
        "Giva silver jewellery",
        "Pipa Bella accessories",
        "Accessorize London India",
        "Claire's accessories mall",
        "Lifestyle department store",
        "Shoppers Stop sale debit",
        "Pantaloons festive shopping",
        "Westside home linen",
        "Marks and Spencer India",
        "Zara India store debit",
        "H&M fast fashion purchase",
        "Uniqlo India launch day",
        "Decathlon hiking pants",
        "Wildcraft rain jacket",
        "Columbia trek shoes import",
        "The North Face jacket",
        "Patagonia fleece rare import",
        "REI gear forwarder fee",
        "AliExpress India customs duty",
        "Shein alternative app order",
        "Meesho reseller stock purchase",
        "GlowRoad reseller bulk",
        "Shop101 social commerce",
        "DealShare grocery bulk",
        "JioMart partner order",
        "Flipkart wholesale B2B",
        "Udaan B2B stock purchase",
        "IndiaMART supplier advance",
        "Alibaba small lot import fee",
        "Customs duty on parcel",
        "Courier COD settlement debit",
        "Blue Dart freight charge",
        "Delhivery logistics fee",
        "DTDC courier prepaid",
        "Professional courier debit",
        "FedEx import duty payment",
        "DHL express surcharge",
        "Aramex customs clearance",
        "Amazon global store import",
        "iHerb supplement import duty",
        "MyProtein import order",
        "Nykaa global beauty import",
        "Sephora India online",
        "LookFantastic subscription",
        "Cult.fit merch store",
        "Nike SNKRS India draw loss",
        "Adidas confirmed app debit",
        "StockX forwarder fee",
        "GOAT sneakers customs",
        "eBay India seller tools",
        "Etsy craft supplies import",
    ]

    # --- EMI ---
    emi_templates = [
        "HDFC home loan EMI auto debit",
        "SBI home loan EMI ECS",
        "ICICI car loan EMI",
        "Axis Bank personal loan EMI",
        "Kotak credit card EMI conversion",
        "HDFC credit card EMI plan",
        "ICICI credit card EMI",
        "SBI SimplyCLICK EMI",
        "American Express EMI charge",
        "Citibank loan EMI",
        "Standard Chartered loan EMI",
        "Yes Bank personal loan EMI",
        "IndusInd two wheeler EMI",
        "Federal Bank gold loan EMI",
        "South Indian Bank housing EMI",
        "Karnataka Bank vehicle EMI",
        "Canara Bank education loan EMI",
        "Union Bank of India EMI",
        "Bank of Baroda home loan EMI",
        "PNB housing finance EMI",
        "Indian Bank mortgage EMI",
        "Indian Overseas Bank EMI",
        "UCO Bank loan EMI",
        "Central Bank of India EMI",
        "IDBI Bank home loan EMI",
        "Bank of Maharashtra EMI",
        "Jammu and Kashmir Bank EMI",
        "Punjab and Sind Bank EMI",
        "Tamilnad Mercantile Bank EMI",
        "DCB Bank personal loan EMI",
        "RBL Bank credit card EMI",
        "AU Small Finance Bank EMI",
        "Ujjivan Small Finance Bank EMI",
        "Equitas EMI on two wheeler",
        "ESAF Small Finance Bank EMI",
        "North East Small Finance Bank EMI",
        "Jana Small Finance Bank EMI",
        "Capital Small Finance Bank EMI",
        "Shivalik Small Finance Bank EMI",
        "Unity Small Finance Bank EMI",
        "Bajaj Finserv consumer EMI",
        "Bajaj Finance EMI debit",
        "Tata Capital personal loan EMI",
        "L&T Finance two wheeler EMI",
        "Mahindra Finance tractor EMI",
        "Cholamandalam vehicle EMI",
        "Shriram Finance gold loan EMI",
        "Muthoot Finance loan EMI",
        "Manappuram gold loan EMI",
        "IIFL Finance EMI",
        "Aditya Birla Housing EMI",
        "LIC Housing Finance EMI",
        "PNB Housing Finance EMI",
        "GIC Housing Finance EMI",
        "HUDCO subsidiary EMI",
        "India Shelter housing EMI",
        "Aptus Value Housing EMI",
        "Home First Finance EMI",
        "Aspire Home Finance EMI",
        "Capri Global Housing EMI",
        "Altico housing loan EMI",
        "Reliance Home Finance EMI legacy",
        "DHFL EMI assignment NBFC",
        "Indiabulls Housing EMI",
        "JM Financial home loan EMI",
        "Motilal Oswal Home Finance EMI",
        "Piramal Capital housing EMI",
        "Fullerton India personal EMI",
        "Hero FinCorp bike EMI",
        "TVS Credit EMI",
        "HDB Financial Services EMI",
        "IDFC FIRST Bank loan EMI",
        "Bandhan Bank housing EMI",
        "CSB Bank gold loan EMI",
        "Karur Vysya Bank EMI",
        "City Union Bank EMI",
        "Tamilnad Mercantile housing EMI",
        "Credit card EMI on electronics",
        "No cost EMI Amazon order",
        "No cost EMI Flipkart order",
        "Debit EMI on POS purchase",
        "BNPL postpaid bill EMI",
        "LazyPay EMI settlement",
        "Simpl pay later EMI",
        "ZestMoney EMI debit",
        "EarlySalary loan EMI",
        "KreditBee EMI repayment",
        "MoneyTap line EMI",
        "Navi loan EMI",
        "Paytm Postpaid EMI",
        "Amazon Pay Later EMI",
        "Flipkart Pay Later EMI",
        "PhonePe postpaid EMI",
        "Cred cash EMI",
        "Slice borrow EMI",
        "Uni card EMI",
        "OneCard EMI conversion",
        "Fi Salary Program EMI",
        "Jupiter loan EMI",
        "NiyoX loan EMI",
        "Freo EMI",
        "Stashfin EMI",
        "SmartCoin EMI",
        "RupeeRedee EMI",
        "CashBean EMI",
        "mPokket student EMI",
        "Propelld education EMI",
        "Avanse education loan EMI",
        "Credila education EMI",
        "Auxilo education EMI",
        "HDFC Credila EMI",
        "Axis education loan EMI",
        "Prodigy Finance EMI INR",
        "Leap finance study EMI",
        "MPOWER financing EMI",
        "Leap Scholar EMI",
        "Education loan moratorium ended EMI",
        "Top-up loan EMI after prepay",
        "Balance transfer EMI card",
        "Loan against property EMI",
        "Loan against FD EMI",
        "Gold loan bullet repayment EMI",
        "Overdraft EMI conversion",
        "OD limit EMI auto debit",
        "Cash credit EMI MSME",
        "Working capital EMI",
        "Machinery loan EMI",
        "CGTMSE backed loan EMI",
        "PMEGP loan EMI",
        "Mudra loan EMI Shishu",
        "Mudra loan EMI Kishor",
        "Mudra loan EMI Tarun",
        "Stand-Up India loan EMI",
        "Startup India seed loan EMI",
        "Venture debt EMI rare",
        "NBFC LAP EMI",
        "Co-lending bank NBFC EMI",
        "Securitisation pool EMI notice",
        "NACH bounce re-present EMI",
        "ECS mandate home loan EMI",
        "SI standing instruction EMI",
        "Auto debit bounce charge plus EMI",
        "Part prepayment EMI reschedule",
        "EMI holiday month catch-up",
        "Moratorium interest capitalisation EMI",
        "Floating rate reset higher EMI",
        "Repo linked loan EMI revision",
        "MCLR linked EMI change",
        "Base rate legacy EMI",
        "BPLR legacy EMI",
        "Teaser rate EMI step-up",
        "Balloon EMI final year",
        "Bullet repayment structured EMI",
        "Hybrid ARM EMI phase 2",
    ]

    # --- Investment ---
    investment_templates = [
        "Zerodha equity buy order",
        "Groww mutual fund SIP",
        "Upstox F&O margin top-up",
        "Angel One brokerage charges",
        "5paisa discount broker debit",
        "Paytm Money MF purchase",
        "ET Money SIP debit",
        "Kuvera direct plan SIP",
        "INDmoney advisory fee",
        "Smallcase rebalance debit",
        "TickerTape premium subscription",
        "Sensibull options toolkit",
        "Streak algo trading fee",
        "TradingView India plan",
        "NSE co-location not retail joke",
        "BSE star MF purchase",
        "CAMS KFin fee",
        "MFU CAN purchase",
        "Nippon India MF SIP",
        "SBI MF regular SIP",
        "HDFC MF direct SIP",
        "ICICI Prudential MF SIP",
        "Axis MF SIP",
        "Kotak MF SIP",
        "Franklin Templeton MF SIP",
        "DSP MF SIP",
        "Mirae Asset MF SIP",
        "Parag Parikh Flexi Cap SIP",
        "Quant MF lumpsum",
        "Edelweiss MF SIP",
        "ITI MF SIP",
        "LIC MF SIP",
        "Tata MF SIP",
        "UTI MF SIP",
        "Aditya Birla Sun Life SIP",
        "HSBC MF SIP",
        "PGIM India MF SIP",
        "Baroda BNP Paribas SIP",
        "Bank of India MF SIP",
        "Canara Robeco SIP",
        "Invesco India MF SIP",
        "Motilal Oswal Midcap SIP",
        "Navi MF SIP",
        "Groww gold lease not",
        "Augmont digital gold buy",
        "SafeGold purchase",
        "MMTC-PAMP gold coin",
        "Jewelery gold ETF not",
        "Sovereign Gold Bond purchase",
        "RBI Retail Direct G-Sec buy",
        "NSC purchase post office",
        "Kisan Vikas Patra deposit",
        "PPF annual contribution",
        "Sukanya Samriddhi deposit",
        "Senior Citizens Savings Scheme",
        "Post office MIS deposit",
        "Corporate bond purchase retail",
        "Edelweiss NCD subscription",
        "Shriram Finance NCD",
        "Muthoottu NCD",
        "JM Financial NCD",
        "IndiaBonds platform fee",
        "GoldenPi charges",
        "TheFixedIncome platform fee",
        "Wint Wealth charges",
        "Grip invest fractional lease",
        "Jiraaf invoice discounting",
        "TradeCred supply chain invest",
        "Liquiloans P2P lending debit",
        "Faircent P2P lend",
        "LenDenClub investment",
        "i2iFunding bid",
        "PropShare fractional realty",
        "Strata prop-tech invest",
        "hBits commercial fractional",
        "RealX tokenized deposit fee",
        "CoinDCX crypto buy",
        "WazirX crypto buy legacy",
        "ZebPay crypto buy",
        "Unocoin BTC buy",
        "Bitbns order fee",
        "Vauld not",
        "Binance P2P INR transfer fee",
        "US stocks INDmoney deposit",
        "Vested US stocks transfer",
        "Winvesta USD funding",
        "Stockal US stocks",
        "DriveWealth IBKR funding",
        "Angel One US stocks beta",
        "NSE IPO application UPI block",
        "BSE SME IPO application",
        "Mainboard IPO mandate",
        "Rights issue application debit",
        "Buyback tender fee",
        "OFS order placement",
        "NCD subscription broker",
        "FPO application debit",
        "QIP not retail",
        "ESOP exercise cashless fee",
        "ESOP exercise cashful debit",
        "RSU vesting tax debit",
        "Employee stock purchase plan",
        "Company NPS contribution employee",
        "NPS Tier-II contribution",
        "NPS Tier-I additional contrib",
        "Atal Pension Yojana debit",
        "EPF voluntary contribution",
        "VPF extra provident fund",
        "Superannuation fund debit",
        "Gratuity fund not",
        "ULIP premium ICICI Prudential",
        "ULIP premium HDFC Life",
        "ULIP premium Max Life",
        "ULIP premium Bajaj Allianz",
        "Term insurance renewal SBI Life",
        "Health insurance renewal Star Health",
        "Motor insurance renewal digit",
        "Travel insurance for visa",
        "Home insurance bundle",
        "Cyber insurance personal",
        "Gold ETF purchase NSE",
        "Silver ETF purchase",
        "REIT units purchase Embassy",
        "REIT units Mindspace",
        "InvIT units purchase IndInfravit",
        "InvIT IRB InvIT toll",
        "Portfolio management service fee",
        "AIF category I commitment",
        "AIF category II drawdown",
        "Angel syndicate SPV contribution",
        "Venture fund LP commitment INR",
        "Pre-IPO unlisted shares deal",
        "Unlistedkart brokerage",
        "TYKE invest platform fee",
        "Altius invest charges",
        "BondsIndia brokerage",
        "Yubi invest fee",
        "Jiraaf processing fee",
        "Grip invest processing fee",
        "Smallcase subscription annual",
        "TickerTape pro plus",
        "Sensibull pro plan",
        "TradingQ&A courses fee",
        "Varsity certificate fee joke",
        "NISM certification exam fee",
        "CFA USD exam INR conversion",
        "FRM exam fee INR",
        "CA course fee debit",
        "CS executive fee",
        "CMA foundation fee",
        "MBA application fee IIM",
        "GRE exam fee INR",
        "TOEFL fee INR",
        "IELTS fee INR",
        "Duolingo English test fee",
        "Coursera subscription INR",
        "Udemy course bulk purchase",
        "LinkedIn Learning INR",
        "Scaler academy EMI education",
        "Newton School ISA not",
        "UpGrad course fee",
        "Great Learning program fee",
        "Simplilearn bootcamp fee",
        "Udacity nanodegree fee",
        "Pluralsight renewal",
        "GitHub Copilot INR",
        "OpenAI API billing INR card",
        "AWS certification voucher",
        "Azure exam fee",
        "GCP skill boost",
        "DigitalOcean droplet INR",
        "Render.com hobby plan",
        "Vercel pro plan INR",
        "Notion team plan INR",
        "Slack paid plan INR",
        "Zoom webinar license",
        "Google Workspace renewal",
        "Microsoft 365 family renewal",
        "Apple iCloud+ India",
        "Dropbox plus renewal",
        "Adobe Creative Cloud India",
        "Canva Pro team India",
        "Figma professional INR",
        "Miro team plan INR",
        "Loom business INR",
        "Calendly pro INR",
        "Grammarly premium INR",
        "Surfshark VPN INR",
        "NordVPN INR",
        "ExpressVPN INR",
        "1Password family INR",
        "Bitwarden premium INR",
        "LastPass premium INR",
        "Password manager not invest joke",
    ]

    for t in food_templates:
        rows.append(row(t, "Food"))
    for t in travel_templates:
        rows.append(row(t, "Travel"))
    for t in shopping_templates:
        rows.append(row(t, "Shopping"))
    for t in emi_templates:
        rows.append(row(t, "EMI"))
    for t in investment_templates:
        rows.append(row(t, "Investment"))

    out_path = "data/financial_transaction_synthetic_templates.csv"
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["Transaction_Text", "Label"])
        w.writeheader()
        w.writerows(rows)

    print(f"Wrote {len(rows)} rows to {out_path}")
    by_label = Counter(r["Label"] for r in rows)
    print("Per label:", dict(by_label))


if __name__ == "__main__":
    main()
